## Практика 14_09_2025 - numpy

In [69]:
import numpy as np

1. Создание массива и базовые операции  
Задача:  Создай массив из чисел от 1 до 10 включительно.
- Найди сумму всех элементов.
- Найди среднее значение.
- Выведи только чётные числа.

In [70]:
def task_1():
    arr = np.arange(1, 11)
    summ = np.sum(arr)
    avg = np.average(arr)
    even_numbers = arr[arr % 2 == 0]

    # Вариант с маской np.where
    # even_numbers_mask = np.where(arr % 2 == 0)
    # even_numbers = arr[even_numbers_mask]

    print(
        f"""
        Сумма элементов -> {summ}
        Среднее значение -> {avg}
        Четные числа -> {even_numbers}
        """)

task_1()


        Сумма элементов -> 55
        Среднее значение -> 5.5
        Четные числа -> [ 2  4  6  8 10]
        


*`np.where` возвращает **индексы**, а не элементы. Чтобы получить элементы нужно использовать булеву маску in-place или булеву маску, полученную с помощью `np.where`. Также можно использовать `np.where(cond, x, y)`, где `x` и `y` - значения, которые будут добавляться по индексу в зависимости от `cond`. При этом нужно указывать и `x`, и `y`.*

2. Индексация и срезы  
Задача:  Создай массив из чисел от 0 до 20.
- Выведи каждый третий элемент.
- Выведи элементы с 5-го по 10-й включительно.
- Замени все элементы больше 15 на 0.

In [71]:
def task_2():
    arr = np.arange(0, 21)
    each_third_elem = arr[::3].copy()
    from_5_to_10_elem = arr[5:11].copy()
    arr[arr > 15] = 0

    # Вариант с созданием копии массива с помощью np.where
    # each_third_elem = arr[::3]
    # from_5_to_10_elem = arr[5:11]
    # replaced_arr = np.where(arr > 15, 0, arr) # np.where возвращает новый массив, если указать x и y

    print(
        f"""
        Каждый третий -> {each_third_elem}
        С 5 по 10 включительно -> {from_5_to_10_elem}
        После замены > 15 = 0 -> {arr}
        """)
    
task_2()


        Каждый третий -> [ 0  3  6  9 12 15 18]
        С 5 по 10 включительно -> [ 5  6  7  8  9 10]
        После замены > 15 = 0 -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  0  0  0  0]
        


*В numpy срезы работают как включения (т.е. если заменить элемент в срезе, то он изменится и в массиве). И наоборот, если изменить элемент в массиве, то и в срезе тоже изменится. Чтобы избежать этого можно использовать `.copy()`.*

3. Работа с многомерными массивами  
Задача:
Создай матрицу 3×3 со случайными числами от 1 до 9.
- Найди сумму всех элементов матрицы.
- Найди максимум и минимум.
- Выведи главную диагональ.

In [72]:
rng = np.random.default_rng(12345)
def task_3():
    matrix = rng.integers(1, 10, size=(3, 3))
    summ = np.sum(matrix)
    max_el, min_el = np.max(matrix), np.min(matrix)
    diag = np.diag(matrix)

    print(f"Матрица ->\n", matrix)
    print(
f"""
Сумма элементов -> {summ}
Максимум и минимум -> {max_el}, {min_el}
Главная диагональ -> {diag}
""")
    
task_3()

Матрица ->
 [[7 3 8]
 [3 2 8]
 [6 7 9]]

Сумма элементов -> 53
Максимум и минимум -> 9, 2
Главная диагональ -> [7 2 9]



4. Векторные операции  
Задача:  
Создай два массива длиной 5 со случайными числами от 0 до 10.
- Посчитай их поэлементную сумму.
- Посчитай их скалярное произведение.
- Посчитай разницу между массивами.

In [73]:
def task_4():
    # reshape - O(1), стоит использовать этот вариант всегда, когда возможно. Здесь - вместо 2 отдельных вызовов
    arr1, arr2 = rng.integers(0, 11, size=(2, 5))
    element_by_summ = arr1 + arr2
    dot_prod = np.dot(arr1, arr2) # dot - скалярное произведение, prod - произведение эл-тов вдоль одной оси
    diff = arr1 - arr2

    print(f"Вектор 1 ->", arr1)
    print(f"Вектор 2 ->", arr2)
    print(
f"""
Сумма элементов -> {element_by_summ}
Скалярное произведение -> {dot_prod}
Разница -> {diff}
""")

task_4()

Вектор 1 -> [4 9 3 6 6]
Вектор 2 -> [2 2 2 7 6]

Сумма элементов -> [ 6 11  5 13 12]
Скалярное произведение -> 110
Разница -> [ 2  7  1 -1  0]



5. Булева маска  
Задача:  
Создай массив из 15 случайных чисел от 0 до 50.
- Выведи только числа больше 25.
- Замени все нечётные числа на -1.
- Подсчитай количество элементов, делящихся на 5.

In [81]:
def task_5():
    arr = rng.integers(0, 51, size=15)
    larger_than_25 = arr[arr > 25]
    replaced_odd_to_minus1 = np.where(arr % 2 == 1, -1, arr)
    count_div_by_5 = np.sum(arr % 5 == 0)

    print(f"Массив ->", arr)
    print(
f"""
Больше 25 -> {larger_than_25}
Нечетные заменить на -1 -> {replaced_odd_to_minus1}
Делятся на 5 -> {count_div_by_5}
""")
    
task_5()

Массив -> [41 11 39 24 20 24 27 13  6 15 50 14 34 13 42]

Больше 25 -> [41 39 27 50 34 42]
Нечетные заменить на -1 -> [-1 -1 -1 24 20 24 -1 -1  6 -1 50 14 34 -1 42]
Делятся на 5 -> 3



### Задачи посложнее

1. Нормализация данных

- Создай массив из 100 случайных чисел (от 10 до 100).
- Приведи все значения к диапазону от 0 до 1 (нормализация).
- Проверь, что минимум массива стал равен 0, а максимум — 1.

In [75]:
def task_6():
    arr = rng.integers(10, 101, size=10)
    largest, smallest = arr.max(), arr.min()
    arr = (arr - smallest) / (largest - smallest)

    print(f"Массив ->\n{arr}")
    print(f"Минимум -> {arr.min()}")
    print(f"Максимум -> {arr.max()}")

task_6()

Массив ->
[0.19047619 0.34920635 0.04761905 0.93650794 1.         0.20634921
 0.92063492 0.         0.44444444 0.11111111]
Минимум -> 0.0
Максимум -> 1.0


2. Генерация и обработка матрицы

- Создай матрицу размером 5×5 со случайными целыми числами от 1 до 20.
- Найди сумму элементов в каждом столбце.
- Найди индекс строки с наибольшей суммой элементов.
- Отсортируй матрицу по значениям первого столбца по убыванию.

In [76]:
def task_7():
    matrix = rng.integers(1, 21, size=(5, 5))
    summ_by_columns = np.sum(matrix, axis=0)
    max_summ_row_idx = np.argmax(np.sum(matrix, axis=1))
    sort_idx = np.argsort(matrix[:, 0])[::-1]
    sorted_matrix = matrix[sort_idx]
    print("Матрица ->\n", matrix)
    print("Сумма по столбцам -> ", summ_by_columns)
    print("Индекс строкми с максимальной суммой -> ", max_summ_row_idx)
    print("Отсортированная матрица по первому столбцу по убыванию ->\n", sorted_matrix)

task_7()

Матрица ->
 [[15  7 10 10 10]
 [ 6 12 17 10  4]
 [ 1  3  2  2  3]
 [12 17 18 14 13]
 [ 7 19 13 15 15]]
Сумма по столбцам ->  [41 58 60 51 45]
Индекс строкми с максимальной суммой ->  3
Отсортированная матрица по первому столбцу по убыванию ->
 [[15  7 10 10 10]
 [12 17 18 14 13]
 [ 7 19 13 15 15]
 [ 6 12 17 10  4]
 [ 1  3  2  2  3]]


3. Работа с линейной алгеброй

- Сгенерируй случайную квадратную матрицу 4×4.
- Найди её определитель.
- Найди обратную матрицу (если существует).
- Проверь, что произведение матрицы и её обратной даёт единичную матрицу (с точностью до округления).

In [ ]:
def task_8():
    matrix = rng.integers(1, 10, size=(4, 4))
    determinant = np.linalg.det(matrix)
    inversed_matrix = np.linalg.inv(matrix)
    must_be_ones_matrix = (matrix @ inversed_matrix)


    print("Матрица ->\n", matrix)
    print("Определитель -> ", determinant.round(2))
    print("Обратная матрица -> ", inversed_matrix)
    print("Произведение матрицы на обратную ->\n", must_be_ones_matrix)

task_8()    


Матрица ->
 [[1 7 6 4]
 [8 4 5 8]
 [5 6 7 5]
 [1 1 5 3]]
Определитель ->  -423.0
Обратная матрица ->  [[-0.24349882 -0.03309693  0.3286052  -0.13475177]
 [ 0.1465721  -0.01891253  0.04491726 -0.21985816]
 [-0.13238771 -0.14420804  0.21749409  0.19858156]
 [ 0.25295508  0.25768322 -0.48699764  0.12056738]]
Произведение матрицы на обратную ->
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


*Чтобы проверить, что поэлементно матрицы примерно равны, следует использовать `np.isclose()` и `np.all_close()`.*  
*Чтобы создать матрицу, все элементы на главной диагонали которой равны 1, а остальные - 0, нужно использовать `np.eye()`.*