## Тема - Арифметические операции

Задача 1.1: Создайте два одномерных массива размером 5 и выполните поэлементные операции: сложение, вычитание, умножение и деление.

In [30]:
import numpy as np

In [31]:
def task_1():
    arr1 = np.array([1, 2, 3, 4, 5])
    arr2 = np.array([6, 7, 8, 9, 10])

    print("+ : ", arr1 + arr2)
    print("- : ",arr2 - arr1)
    print("* : ", arr1 * arr2)
    print("/ : ", arr2 / arr1)

task_1()


+ :  [ 7  9 11 13 15]
- :  [5 5 5 5 5]
* :  [ 6 14 24 36 50]
/ :  [6.         3.5        2.66666667 2.25       2.        ]


Задача 1.2: Создайте матрицу 3x3 и выполните операции с скаляром: умножение на 2, деление на 3, возведение в квадрат.

In [36]:
def task_2():
    matrix = np.arange(9).reshape(3, 3)
    print(matrix)
    print(*matrix * 2)
    print(*matrix / 2)
    print(*matrix ** 2)

task_2()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 2 4] [ 6  8 10] [12 14 16]
[0.  0.5 1. ] [1.5 2.  2.5] [3.  3.5 4. ]
[0 1 4] [ 9 16 25] [36 49 64]


Задача 1.3: Создайте два массива разной размерности (3x1 и 1x3) и продемонстрируйте работу broadcasting при сложении.

In [39]:
def task_3():
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([[4], [5], [6]])

    print(arr1 * arr2)

task_3()

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
