## Тема - Прихотливое индексирование

In [1]:
import numpy as np

Задача 3.1: Создайте массив и получите элементы по индексам [0, 2, 4, 6, 8] с помощью массива индексов.

In [ ]:
def task_1():
    arr = np.arange(0, 10)
    print(arr[[0, 2, 4, 6, 8]])

task_1()

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


Задача 3.2: Создайте матрицу и получите элементы, удовлетворяющие условию: значения больше 5.

In [ ]:
def task_2():
    matrix = np.arange(1, 10).reshape(3, 3)
    print(matrix[matrix > 5])
  
# Второй способ
# def task_2():
#     matrix = np.arange(1, 10).reshape(3, 3)
#     result = np.where(matrix > 5)
#     print(matrix[result])

task_2()

[6 7 8 9]
