## Тема - Прихотливое индексирование

In [2]:
import numpy as np

Задача 3.1: Создайте массив и получите элементы по индексам [0, 2, 4, 6, 8] с помощью массива индексов.

In [3]:
def task_1():
    arr = np.arange(0, 10)
    print(arr[[0, 2, 4, 6, 8]])

task_1()

[0 2 4 6 8]


Задача 3.2: Создайте матрицу и получите элементы, удовлетворяющие условию: значения больше 5.

In [4]:
def task_2():
    matrix = np.arange(1, 10).reshape(3, 3)
    print(matrix[matrix > 5])
  
# Второй способ
# def task_2():
#     matrix = np.arange(1, 10).reshape(3, 3)
#     result = np.where(matrix > 5)
#     print(matrix[result])

task_2()

[6 7 8 9]


Задача 3.3: Используя булево индексирование, замените все отрицательные элементы в массиве на 0.

In [11]:
def task_3():
    arr = np.random.randint(-10, 10, 10)
    print(arr)
    arr[arr < 0] = 0
    print(arr)

task_3()

[ 9  9 -2 -5  5  5 -1  7 -4  2]
[9 9 0 0 5 5 0 7 0 2]
