## Тема - Транспонирование и перестановка осей

In [2]:
import numpy as np

Задача 4.1: Создайте матрицу 2x3 и транспонируйте её.

In [3]:
def task_1():
    matrix = np.arange(0, 6).reshape(2, 3)
    print(matrix.T)

task_1()

[[0 3]
 [1 4]
 [2 5]]


Задача 4.2: Создайте трехмерный массив (2x3x4) и поменяйте местами первую и последнюю оси.

In [14]:
def task_2():
    matrix = np.arange(0, 24).reshape(2, 3, 4)
    print(matrix)
    print('------------')
    print(matrix.swapaxes(0, 2))

task_2()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
------------
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


Задача 4.3: Для матрицы 5x5 найдите разницу между исходной матрицей и её транспонированной версией.

In [15]:
def task_3():
    matrix = np.arange(0, 25).reshape(5, 5)
    print(matrix - matrix.T)

task_3()

[[  0  -4  -8 -12 -16]
 [  4   0  -4  -8 -12]
 [  8   4   0  -4  -8]
 [ 12   8   4   0  -4]
 [ 16  12   8   4   0]]
