## Универсальные функции (u-функции)
Универсальной функцией называется функция, которая выполняет поэлементные операции над данными, хранящимися в объектах `ndarray`. Можно считать, что это векторные обертки вокруг простых функций. 

Многие u-функции - простые поэлементные операции, например `numpy.sqrt` и `numpy.exp`:

In [4]:
import numpy as np

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Такие u-функции называются *унарными*. Другие, например `numpy.add` или `numpy.maximum` принимают два массива и возвращают один результирующий - *бинарные*.

In [16]:
rng = np.random.default_rng(12346) # если seed указан, то при перезапусках результат не меняется
x = rng.integers(0, 10, 5)
y = rng.integers(0, 10, 5)

np.maximum(x, y)

array([6, 6, 8, 4, 4])

[Список u-функций на данный момент](https://numpy.org/doc/stable/reference/ufuncs.html)