## Numpy - база

Numpy - один из важнейших пакетов для численных расчетов в  Python.
Numpy предлагает:
- **ndarray**, эффективный многомерный массив, предоставляющий быстрые арифметические операции с массивами и гибкий механизм укладывания;
- математические функции для выполнения быстрых операций над целыми массивами без явного выписывания циклов;
- средства для чтения массива данных с диска и записи его на диск, а также для работы с проецируемыми на память файлами;
- алгоритмы линейной алгебры, генерация случайных чисел и преобразование Фурье;
- средства для интеграции с кодом, написанным на C, C++ или Fortran.


NumPy **хранит данные в непрерывном блоке памяти** независимо от других встроенных объектов Python. Алгоритмы NumPy, написанные на языке C, могут работать с  этим блоком, не  обременяя себя проверкой типов и другими накладными расходами. Массивы NumPy **потребляют гораздо меньше памяти**, чем встроенные в Python последовательности.

В NumPy сложные **операции применяются к массивам целиком**, так что отпадает необходимость в циклах for, которые для больших последовательностей могут **работать медленно**. NumPy быстрее кода на чистом Python, потому что в  написанных на C  алгоритмах **нет накладных расходов**, свойственных обычному интерпретируемому Python-коду.

Рассмотрим массив NumPy, содержащий 1 миллион чисел и аналогичный список Python:

In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

1.71 ms ± 32.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
36.3 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### **ndarray** - объект многомерного массива
Одна из ключевых особенностей NumPy - объект `ndarry` для представления N-мерного массива; это быстрый и гибкий контейнер для хранения больших наборов данных в Python. Массивы позволяют **применять математические операции к блокам данных, используя тот же синтаксис, что и со скалярами**.

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

print("Data ==>\n", data)
print("Data * 10 ==>\n", data * 10)
print("Data + Data ==>\n", data + data)

Data ==>
 [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
Data * 10 ==>
 [[ 15.  -1.  30.]
 [  0. -30.  65.]]
Data + Data ==>
 [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
